<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260423150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add organizer access requests for admin approval workflow';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.'
        );

        $this->addSql('CREATE TABLE organizer_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, reviewed_by_id INT DEFAULT NULL, motivation TEXT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_organizer_request_user_status_created_at ON organizer_request (user_id, status, created_at)');
        $this->addSql('CREATE INDEX idx_organizer_request_status_created_at ON organizer_request (status, created_at)');
        $this->addSql('ALTER TABLE organizer_request ADD CONSTRAINT FK_6056F028A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organizer_request ADD CONSTRAINT FK_6056F0285B932535 FOREIGN KEY (reviewed_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.'
        );

        $this->addSql('DROP TABLE organizer_request');
    }
}
